- workflow_id: a957da0e6fed152b
  output_history_base_name: DNA 16C 50G-MEM
  runs:
    - history_name: HG00171
      inputs:
      - name: FASTQ Dataset
        dataset_id: e49d4a2f705b9571
    - history_name: HG00152
      inputs:
      - name: FASTQ Dataset
        dataset_id: 234de07cebbc5c94
    - history_name: HG00599
      inputs:
      - name: FASTQ Dataset
        dataset_id: 6e64073425d9dad5
    - history_name: HG01167
      inputs:
      - name: FASTQ Dataset
        dataset_id: 6ae43b3a46b25f74
    - history_name: HG003
      inputs:
      - name: FASTQ Dataset
        dataset_id: dbafe90fc7cff8d0
- workflow_id: b94314cb9cb46380
  output_history_base_name: PairedDNA 16C 50G-MEM
  runs:
    - history_name: SRS9540951
      inputs:
      - name: FASTQ Dataset
        dataset_id: f0fd4a09540cb16f