- workflow_id: Benchmarking RNA-seq Cloud Costs
  output_history_base_name: Workflow Testing - RNA-SEQ Paired
  reference_data:
  - dataset_id: gencode.v38.transcripts.fa.gz
    name: Reference Transcript (FASTA)
  runs:
  - history_name: SRS9276533
    inputs:
    - dataset_id: SRR14916263 (fastq-dump)
      name: FASTQ RNA Dataset
  - history_name: SRS9276520
    inputs:
    - dataset_id: SRR14916277 (fastq-dump)
      name: FASTQ RNA Dataset
  - history_name: SRS9276534
    inputs:
    - dataset_id: SRR14916264 (fastq-dump)
      name: FASTQ RNA Dataset
- workflow_id: Benchmarking RNA Single-Read Cloud Costs
  output_history_base_name: Workflow Testing - RNA Single
  reference_data:
  - dataset_id: gencode.v38.transcripts.fa.gz
    name: Reference Transcript (FASTA)
  runs:
  - history_name: SRS9551191
    inputs:
    - dataset_id: SRR15206520 (fastq-dump)
      name: FASTQ RNA Dataset
  