workflow_id: 3606d3101a772650
inputs:
  - name: Reference FASTA
    id: '3947ba9ca107312f'
  - name: GTF
    id: '048a970701a6dc44'
  - name: FASTA Dataset
    id: 'ca5081d2c8f1088a'
output_history_name: RNA seq test results

